<?php
//require_once 'headers.php';
//$redicet = $_SERVER['HTTP_REFERER'];

$postData= file_get_contents('php://input');

if(isset($postData)){
	$newPost = json_decode($postData);
	$idUser = $newPost->idUser;
	$content = $newPost->json;
	$response = new Post();
	$response->sendPost($idUser, $content);
}
else echo "I don't see anything";

class Post{
	function sendPost($user, $json){
		$result = "Empty";
		$isPrivate = 0;
		if($json->isPrivate == 'true') $isPrivate = 1;
		// Create connection
		require_once 'DBconfig.php';
		$conn = new mysqli($HostName, $HostUser, $HostPass, $DatabaseName);
		if ($conn->connect_error) {
		 $result = "Connection failed: " . $conn->connect_error;
		}
		else{
			// Inserting primary info
			$sql = "INSERT INTO Post (Name, lat, lng, comment, date, Users_idUsers, type, isCheck, isPrivate)
				VALUES ('".$json->name."', 
					".$json->position->lat.", 
					".$json->position->lng.",
					'".$json->description."',
					'".$json->dateTime."',
					'".$user."',
					1,
					0,
					".$isPrivate.")";
			if($conn->query($sql)){
			//If successful inserted then...
				$result = "Successful";
				//Getting autogenerated Id of post
				$getIDPost = "SELECT idPost FROM Post WHERE Name ='".$json->name."' 
										AND date='".$json->dateTime."' 
										AND Users_idUsers='".$user."'";
				$res = $conn->query($getIDPost);
				while($row = $res->fetch_assoc()) {
					$ID = $row["idPost"];
				 }
				// then insert photoes with post id
				foreach($json->photoes as $photo){
					$insertPhotoes = "INSERT INTO Photoes (fileName, Content, Post_IdPost)
							VALUES('".$photo->name."',
								'".$photo->blob."',
								'".$ID."')";
					if($conn->query($insertPhotoes)){
						$result = "Successful";					
					}
					else{
						$result = "Photo Insert Error ".$conn->error;				
					}
				}
			}
			else{
				$result = "Insert Error ".$conn->error;		
			}
			$conn->close();	
		}
		$answer = '{"operation":"createpost","result":"'.$result.'"}';
		echo $answer;
	}
}
	
?>
