<?php
//require_once 'headers.php';
//$redicet = $_SERVER['HTTP_REFERER'];

$postData= file_get_contents('php://input');

if(isset($postData)){
	$data = json_decode($postData);
	$operation = $data->operation;
	if($operation == 'create post'){
		$idUser = $data->json->idUser;
		$content = $data->json->data;
		$response = new Post();
		$response->sendPost($idUser, $content);
	}
	else if($operation == "edit post"){
		$idUser = $data->json->idUser;
		$content = $data->json->data;
		$response = new Post();
		$response->editPost($idUser, $content);
	}
	else if($operation == 'create comment'){
		$response = new Post();
		$response->sendComment($data->json);
	}
	else if($operation == 'set rating'){
		$idUser = $data->json->idUser;
		$content = $data->json->data;
		$response = new Post();
		$response->setRating($idUser, $content);
	}
	else echo '{"operation":"'.$operation.'","result":"Unknown operation"}';
}
else echo '{"operation":"createpost","result":"POST Error"}';

class Post{
	function sendPost($user, $json){
		$result = "Empty";
		$isPrivate = 0;
		if($json->isPrivate == 'true') $isPrivate = 1;
		// Create connection
		require_once 'DBconfig.php';
		$conn = new mysqli($HostName, $HostUser, $HostPass, $DatabaseName);
		if ($conn->connect_error) {
		 $result = "Connection failed: " . $conn->connect_error;
		}
		else{
			// Inserting primary info
			$sql = "INSERT INTO Post (Name, lat, lng, comment, date, Users_idUsers, type, isCheck, isPrivate)
				VALUES ('".$json->name."', 
					".$json->position->lat.", 
					".$json->position->lng.",
					'".$json->description."',
					'".$json->dateTime."',
					'".$user."',
					1,
					0,
					".$isPrivate.")";
			if($conn->query($sql)){
			//If successful inserted then...
				$result = "Successful";
				//Getting autogenerated Id of post
				$getIDPost = "SELECT idPost FROM Post WHERE Name ='".$json->name."' 
										AND date='".$json->dateTime."' 
										AND Users_idUsers='".$user."'";
				$res = $conn->query($getIDPost);
				while($row = $res->fetch_assoc()) {
					$ID = $row["idPost"];
				 }
				// then insert photoes with post id
				foreach($json->photoes as $photo){
					if(!is_dir("/srv/windows/dyploma/Photoes/".$ID."/")){
						mkdir("/srv/windows/dyploma/Photoes/".$ID."/");
					}
					date_default_timezone_set('Europe/Kiev');
					$t =time();
					$photoName = date('Y-m-d H:i:s',$t)."-".$photo->name;
					$blob = str_replace("data:image/jpeg;base64,", "", $photo->blob);
					$image = base64_decode($blob);
					if(file_exists("/srv/windows/dyploma/Photoes/All/".$photoName)){
						$photoName='1-'.$photoName;
						file_put_contents("/srv/windows/dyploma/Photoes/".$ID."/".$photoName,$image);
					}
					else{
						file_put_contents("/srv/windows/dyploma/Photoes/".$ID."/".$photoName,$image);
					}
					$insertPhotoes = "INSERT INTO Photoes (fileName, Post_IdPost)
							VALUES('".$photoName."',
								'".$ID."')";
					if($conn->query($insertPhotoes)){
						$result = "Successful";					
					}
					else{
						$result = "Photo Insert Error ".$conn->error;				
					}
				}
			}
			else{
				$result = "Insert Error ".$conn->error;		
			}
			$conn->close();	
		}
		$answer = '{"operation":"createpost","result":"'.$result.'"}';
		echo $answer;
	}
	function editPost($user, $json){
		$result = "";
		$ArrivedUserId = $user;
		$postID = 0;
		$postName = "";
		$postDescription = "";
		$postLat = 0;
		$postLng = 0;
		if($json->description === "" || $json->Name === "" || count($json->photoes)===0){
			$result = "Error in change";
		}
		else{
			$ArrivedUsername = $json->username;
			require_once 'DBconfig.php';
			$conn = new mysqli($HostName, $HostUser, $HostPass, $DatabaseName);
			if ($conn->connect_error) {
			 $result = "Connection failed: " . $conn->connect_error;
			}
			$sql = "SELECT Post.idPost, Post.Name, Post.comment, lat, lng FROM Users JOIN Post WHERE username='".$ArrivedUsername."' AND idUsers=".$ArrivedUserId." AND Post.idPost=".$json->idPost." AND Post.Users_idUsers=Users.idUsers";
			$res = $conn->query($sql);
			if ($res->num_rows >0) {
				while($row = $res->fetch_assoc()) {
				 	$postName = $row["Name"];
					$postDescription = $row["comment"];
					$postLat = $row["lat"];
					$postLng = $row["lng"];
					$postID = $row["idPost"];
				 }
			$update = "UPDATE Post SET ";
				if($json->Name != $postName){ 
					$update.= "Post.Name = '".$json->Name."', ";
					$result.= "The name was edited from ".$postName." to ".$json->Name."; ";
				}
				if($json->description != $postDescription){ 
					$update.= "Post.comment = '".$json->description."', ";
					$result.= "The description was edited from ".$postDescription." to ".$json->description."; ";
				}
				if($json->position->lat != $postLat){ 
					$update.= "lat = '".$json->position->lat."', ";
					$result.= "The Lat was edited from ".$postLat." to ".$json->position->lat."; ";
				}
				if($json->position->lng != $postLng){ 
					$update.= "lng = '".$json->position->lng."', ";
					$result.= "The Lng was edited from ".$postLng." to ".$json->position->lng."; ";
				}
			$update = substr($update,0,(strlen($update)-2));
			$update.= " WHERE Users_idUsers=".$ArrivedUserId." AND Post.idPost = ".$postID."";
			
			$deleteOldPhotoes = "DELETE FROM Photoes WHERE Post_idPost=".$postID."";
			$conn->query($deleteOldPhotoes);

			foreach($json->photoes as $photo){
				$insertNewPhoto = "INSERT INTO Photoes (fileName, Content, Post_idPost) VALUES ('".$photo->name."', '".$photo->blob."', ".$postID.")";
				if($conn->query($insertNewPhoto)){
					$result.= " Photo inserted. ";
				}
			}
			if($conn->query($update)){
				$result.= " Operation Successful. ";
			}
			else{
				$result.= "Insert Error ".$conn->error;				
			}
			$conn->close();
			} else {
				$result = 'No Results Found';
			}
		}
		echo '{"operation":"Edit Post","result":"'.$result.'"}';
	}
	function sendComment($data){
		$result = "Empty";
		$idUser = $data->idUser;
		$content = $data->data->content;
		$rating = $data->data->rating;
		$date = $data->data->date;
		$idPost = $data->data->idPost;
		// Create connection
		require_once 'DBconfig.php';
		$conn = new mysqli($HostName, $HostUser, $HostPass, $DatabaseName);
		if ($conn->connect_error) {
		 $result = "Connection failed: " . $conn->connect_error;
		}
		else{
			// Inserting primary info
			$sql = "INSERT INTO Comments (Content, rating, date, Post_idPost, Users_idUsers)
				VALUES ('".$content."', 
					".$rating.", 
					'".$date."',
					".$idPost.",
					".$idUser.")";
			if($conn->query($sql)){
			//If successful inserted then...
				$result = "Successful";
			}
			else{
				$result = "Insert Error ".$conn->error.$sql;		
			}
			$conn->close();	
		}
		$answer = '{"operation":"createcomment","result":"'.$result.'"}';
		echo $answer;
		
	}
	function setRating($idUser, $content){
		$result = "Empty";
		$rate = 1;
		$sql = '';
		$setter = $content->setting;
		$idPost = $content->idPost;
		$rateType = $content->type;
		// Create connection
		require_once 'DBconfig.php';
		$conn = new mysqli($HostName, $HostUser, $HostPass, $DatabaseName);
		if ($conn->connect_error) {
		 $result = "Connection failed: " . $conn->connect_error;
		}
		else{
			if($setter == "like") $rate = 1; else $rate = -1;
			$checkRateByMe = "SELECT rating FROM Post_has_Rate
						WHERE Post_has_Rate.postId=$idPost
						AND Post_has_Rate.userId=$idUser";
			
			$getMyPostsRate = $conn->query($checkRateByMe);
			
			if ($getMyPostsRate->num_rows>0) {
				if($rateType==='inversion'){
					$sql = "DELETE FROM Post_has_Rate WHERE postId=$idPost AND userId=$idUser";
				}
				else 	$sql = "UPDATE Post_has_Rate SET rating=$rate WHERE postId=$idPost AND userId=$idUser";
			}
			else{
				$sql = "INSERT INTO Post_has_Rate VALUES($idPost,$idUser,$rate)";
			}

			if($conn->query($sql)){
			//If successful inserted then...
				$getLikes = "SELECT userId FROM Post_has_Rate JOIN Post 
						WHERE Post.idPost=Post_has_Rate.postId
						AND Post_has_Rate.rating=1 
						AND Post_has_Rate.postId=$idPost";

				$getDislikes = "SELECT userId FROM Post_has_Rate JOIN Post 
						WHERE Post.idPost=Post_has_Rate.postId
						AND Post_has_Rate.rating=-1 
						AND Post_has_Rate.postId=$idPost";
				
				$getPostLikes = $conn->query($getLikes);
				$getPostDislikes = $conn->query($getDislikes);
				$row["IdPost"] = $idPost;
				$row["rating"]["likes"] = (int)$getPostLikes->num_rows;
				$row["rating"]["dislikes"] = (int)$getPostDislikes->num_rows;
				$row["rating"]["isLikedByMe"] = false;
				$row["rating"]["isDislikedByMe"] = false;
				
				if ($getPostLikes->num_rows>0) {
					while($like = $getPostLikes->fetch_assoc()) {
						if((int)$like['userId']===$idUser) $row["rating"]["isLikedByMe"]=true;
					}
				}
				if ($getPostDislikes->num_rows>0) {
					while($dislike = $getPostDislikes->fetch_assoc()) {
						if((int)$dislike['userId']===$idUser) $row["rating"]["isDislikedByMe"]=true;
					}
				}
				$json = $row;
			}
			else{
				$json = "Insert Error ".$conn->error.$sql;		
			}
			$conn->close();	
		}
		$answer = '{"operation":"set rating","result":'.json_encode($json).'}';
		echo $answer;
		
	}
}
	
?>
